version: 2.1
orbs:
  ship: auth0/ship@0.2.0
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: sudo npm install -g npm@latest
      - ship/node-install-packages
      - run:
          name: Run Tests
          command: npm run test:ci
      - run:
          name: Run End to End Tests
          command: npm run test:end-to-end
      - run:
          name: Run Lint
          command: npm run lint
      - store_artifacts:
          path: ./coverage/lcov-report
      - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  build-and-test:
    jobs:
      - build
      - ship/node-publish:
          requires:
            - build
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master